
/* Table data export for table inventory_source */

/* Preserve session variables */
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS=0;

/* Export data */
INSERT INTO `inventory_source` (`source_code`,`name`,`enabled`,`description`,`latitude`,`longitude`,`country_id`,`region_id`,`region`,`city`,`street`,`postcode`,`contact_name`,`email`,`phone`,`fax`,`use_default_carrier_config`,`is_pickup_location_active`,`frontend_name`,`frontend_description`) VALUES ("akron_oh","Akron OH",1,NULL,"41.062164","-81.430720","US",47,"Ohio","Akron","2700 Gilchrist Rd","44305",NULL,"sales@barrdisplay.com","800-222-2702",NULL,1,1,"Akron OH","<p>Current hours for pick up: Monday-Friday 8:30am-3:30pm  (Closed for Lunch 12-1)</p>");
INSERT INTO `inventory_source` (`source_code`,`name`,`enabled`,`description`,`latitude`,`longitude`,`country_id`,`region_id`,`region`,`city`,`street`,`postcode`,`contact_name`,`email`,`phone`,`fax`,`use_default_carrier_config`,`is_pickup_location_active`,`frontend_name`,`frontend_description`) VALUES ("baltimore_md","Baltimore MD",1,NULL,"39.239959","-76.599613","US",31,"Maryland","Baltimore","362 Brickyard Hill Rd","21225",NULL,"sales@barrdisplay.com","800-222-2702",NULL,1,1,"Baltimore MD","<p>Hours for pick up: Monday-Friday 8:00am-3:30pm</p>");
INSERT INTO `inventory_source` (`source_code`,`name`,`enabled`,`description`,`latitude`,`longitude`,`country_id`,`region_id`,`region`,`city`,`street`,`postcode`,`contact_name`,`email`,`phone`,`fax`,`use_default_carrier_config`,`is_pickup_location_active`,`frontend_name`,`frontend_description`) VALUES ("birmingham_al","Birmingham AL",1,NULL,"33.176497","-86.761186","US",1,"Alabama","Calera","3280 US-31","35040",NULL,"sales@barrdisplay.com","800-222-2702",NULL,1,1,"Birmingham AL","<p>Current hours for pick up: Monday-Friday 7:30am-3:30pm</p>");
INSERT INTO `inventory_source` (`source_code`,`name`,`enabled`,`description`,`latitude`,`longitude`,`country_id`,`region_id`,`region`,`city`,`street`,`postcode`,`contact_name`,`email`,`phone`,`fax`,`use_default_carrier_config`,`is_pickup_location_active`,`frontend_name`,`frontend_description`) VALUES ("charleston_sc","Charleston SC",1,NULL,"32.794481","-80.051726","US",54,"South Carolina","Charleston","620 Dobbin Road","29414",NULL,"sales@barrdisplay.com","800-222-2702",NULL,1,1,"Charleston SC","<p>Hours for pick up: Monday-Thursday 9:00am-3:00pm, Fridays 9:00am-12:00pm</p>");
INSERT INTO `inventory_source` (`source_code`,`name`,`enabled`,`description`,`latitude`,`longitude`,`country_id`,`region_id`,`region`,`city`,`street`,`postcode`,`contact_name`,`email`,`phone`,`fax`,`use_default_carrier_config`,`is_pickup_location_active`,`frontend_name`,`frontend_description`) VALUES ("chesapeake_va","Chesapeake VA",1,NULL,"36.784332","-76.373315","US",61,"Virginia","Chesapeake","3804 Cook Blvd #15","23323",NULL,"sales@barrdisplay.com","800-222-2702",NULL,1,1,"Chesapeake VA","<p>Current hours for pick up: Monday-Friday 8:00am-4:00pm</p>");
INSERT INTO `inventory_source` (`source_code`,`name`,`enabled`,`description`,`latitude`,`longitude`,`country_id`,`region_id`,`region`,`city`,`street`,`postcode`,`contact_name`,`email`,`phone`,`fax`,`use_default_carrier_config`,`is_pickup_location_active`,`frontend_name`,`frontend_description`) VALUES ("dania_beach","Dania Beach FL",1,NULL,"26.050652","-80.170816","US",18,"Florida","Dania Beach","2303 Stirling Road","33312",NULL,"sales@barrdisplay.com","800-222-2702",NULL,1,1,"Dania Beach FL","<p>Current hours for pick up: Monday-Friday 9:00am-4:30pm</p>");
INSERT INTO `inventory_source` (`source_code`,`name`,`enabled`,`description`,`latitude`,`longitude`,`country_id`,`region_id`,`region`,`city`,`street`,`postcode`,`contact_name`,`email`,`phone`,`fax`,`use_default_carrier_config`,`is_pickup_location_active`,`frontend_name`,`frontend_description`) VALUES ("fort_myers","Fort Myers FL",1,NULL,"26.658412","-81.807780","US",18,"Florida","Fort Myers","5770 ZIP DRIVE","33905","NULL","sales@barrdisplay.com","800.330.3049",NULL,1,1,"Fort Myers FL","<p><strong>We will be open M-TH 8:30-5pm and F 8:30-4:30 pm.</strong></p>");
INSERT INTO `inventory_source` (`source_code`,`name`,`enabled`,`description`,`latitude`,`longitude`,`country_id`,`region_id`,`region`,`city`,`street`,`postcode`,`contact_name`,`email`,`phone`,`fax`,`use_default_carrier_config`,`is_pickup_location_active`,`frontend_name`,`frontend_description`) VALUES ("mobile_al","Mobile AL",1,NULL,"30.809021","-88.062662","US",1,"Alabama","Saraland","245 Jacintoport Blvd","36571","NULL","sales@barrdisplay.com","800-222-2702",NULL,1,1,"Mobile AL","<p>Hours for pick up: Monday-Friday 8:00am-4:30pm CST</p>");
INSERT INTO `inventory_source` (`source_code`,`name`,`enabled`,`description`,`latitude`,`longitude`,`country_id`,`region_id`,`region`,`city`,`street`,`postcode`,`contact_name`,`email`,`phone`,`fax`,`use_default_carrier_config`,`is_pickup_location_active`,`frontend_name`,`frontend_description`) VALUES ("nashville_tn","Nashville TN",1,NULL,"36.215170","-86.768414","US",56,"Tennessee","Nashville","2610 Hart St","37207",NULL,"sales@barrdisplay.com","800-222-2702",NULL,1,1,"Nashville TN","<p>Hours for pick up: Fridays 1:00pm-4:00pm</p>");
INSERT INTO `inventory_source` (`source_code`,`name`,`enabled`,`description`,`latitude`,`longitude`,`country_id`,`region_id`,`region`,`city`,`street`,`postcode`,`contact_name`,`email`,`phone`,`fax`,`use_default_carrier_config`,`is_pickup_location_active`,`frontend_name`,`frontend_description`) VALUES ("oklahoma_city","Oklahoma City OK",1,"35.47278641428707, -97.62116301591354","35.472786","-97.621163","US",48,"Oklahoma","Oklahoma City","6200 Melrose Ln","73127",NULL,"sales@barrdisplay.com","800-222-2702",NULL,1,1,"Oklahoma City OK","Current hours for pick up: Monday-Friday 9:00am-4:00pm");
INSERT INTO `inventory_source` (`source_code`,`name`,`enabled`,`description`,`latitude`,`longitude`,`country_id`,`region_id`,`region`,`city`,`street`,`postcode`,`contact_name`,`email`,`phone`,`fax`,`use_default_carrier_config`,`is_pickup_location_active`,`frontend_name`,`frontend_description`) VALUES ("orlando_hq","Orlando FL - Headquarters",1,NULL,"28.582919","81.426278","US",18,"Florida","Orlando","3033 Mercy Drive","32808","NULL","sales@barrdisplay.com","800.222.2702","407.297.0494",1,1,"Orlando FL","<p><em>Showroom Hours: Mon - Fri: 8:30am - 5pm EST</em></p>\r\n<p> </p>\r\n<h2> </h2>");
INSERT INTO `inventory_source` (`source_code`,`name`,`enabled`,`description`,`latitude`,`longitude`,`country_id`,`region_id`,`region`,`city`,`street`,`postcode`,`contact_name`,`email`,`phone`,`fax`,`use_default_carrier_config`,`is_pickup_location_active`,`frontend_name`,`frontend_description`) VALUES ("pittsburgh_pa","Pittsburgh PA",1,NULL,"40.200511","-79.625779","US",51,"Pennsylvania","Ruffs Dale","362  Brickyard Hill Rd","15679",NULL,"sales@barrdisplay.com","800-222-2702",NULL,1,1,"Pittsburgh PA","<p>Hours for pick up: Monday-Friday 7:00am-3:30pm</p>");
INSERT INTO `inventory_source` (`source_code`,`name`,`enabled`,`description`,`latitude`,`longitude`,`country_id`,`region_id`,`region`,`city`,`street`,`postcode`,`contact_name`,`email`,`phone`,`fax`,`use_default_carrier_config`,`is_pickup_location_active`,`frontend_name`,`frontend_description`) VALUES ("tampa_fl","Tampa FL",1,NULL,"27.982149","-82.353785","US",18,"Florida","Tampa","9110 KING PALM DRIVE","33619",NULL,"sales@barrdisplay.com","813-628-4332",NULL,1,1,"Tampa FL","<p>The Showroom is now open M-F 8:30am-5:00 pm</p>");
INSERT INTO `inventory_source` (`source_code`,`name`,`enabled`,`description`,`latitude`,`longitude`,`country_id`,`region_id`,`region`,`city`,`street`,`postcode`,`contact_name`,`email`,`phone`,`fax`,`use_default_carrier_config`,`is_pickup_location_active`,`frontend_name`,`frontend_description`) VALUES ("tusla_ok","Tulsa OK",1,NULL,"36.086690","-95.852586","US",48,"Oklahoma","Tusla","5400 S Garnett Rd","74146",NULL,"sales@barrdisplay.com","800-222-2702",NULL,1,1,"Tulsa OK","<p>Current hours for pick up: Monday-Friday 9:00am-4:00pm</p>");

/* Restore session variables to original values */
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
